### ISSUE TITLE
Add 'flex-' prefix for 'start' & 'end' flex values

### ISSUE THREAD

**Issue by Abogical** [csstools/postcss-plugins#108]
Spec: https://www.w3.org/TR/css-align/#positional-values

'start' & 'end' values were added to replace the 'flex-start' & 'flex-end' respectively. Unfortunately at this time, only Safari & Firefox support these values, so we have to add the `flex-` prefix to them. This plugin does not add these values even with stage 0.

**Comment by romainmenke** [comment]
Looked into this and this seems unrelated to logical.

I am also unsure if `start` and `end` can be safely converted to flex-start` and `flex-end`.
From what I can tell these are two different features that happen to have similar effects in some cases.

We would have to ask for clarification here.

**Comment by romainmenke** [comment]
@Abogical we can not add a plugin for this because it isn't a safe transform.

`start` and `flex-start` are not the same thing.
They only happen to have the same effect within a `flex` context.

We can not determine from static CSS if `align-items: start;` will be applied on an element within a `flex` context.

It is best to use the correct values for each case. If your case requires `flex-start` you should use exactly that.

**Comment by Abogical** [comment]
Yeah it seems the specs may have changed since I last saw this. Thanks anyway!
