### ISSUE TITLE
Negative queries generated by custom-media plugin are broken on Safari < 17

### ISSUE THREAD

**Issue by escaton** [csstools/postcss-plugins#1493]
### Bug description

When combining several custom media queries, the custom-media plugin unwraps the expression and generates a series of duplicates with negative predicates. It works fine, but unfortunately, Safari had a bug with such negative predicates until version 17 (released in 2022), which resulted in just ignoring the whole media query.

Search for "Fixed negative resolutions in Media Queries to be invalid"
https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes

### Source CSS

```
/* I also use postcss-media-minmax, but it doesn't affect the custom-media generation */ 

@custom-media --mobile (width <= 480px) or ((height <= 480px) and (orientation: landscape));
@custom-media --tablet-plus (width > 480px) and (height > 480px);

@media (--mobile) or (--tablet-plus) {...}
```

### Expected CSS

```
@media (
		(width <= 480px) or ((height <= 480px) and (orientation: landscape))
	) or (
		(width > 480px) and (height > 480px)
	) {
	...
}
```

### Actual CSS

```
@media not all and ( (min-width: 481px) and (min-height: 481px)) {
	@media (max-color:2147477350) or (color:2147477350) {
		...
	}
}
@media not all and ( (max-width: 480px) or ((max-height: 480px) and (orientation: landscape))) {
	@media (min-width: 481px) and (min-height: 481px) {
		@media (color:2147477350) or (max-color:2147477350) {
			...
		}
	}
}
@media not all and ( (min-width: 481px) and (min-height: 481px)) {
	@media (color:2147477350) or (color:2147477350) {
		...
	}
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### What plugin are you experiencing this issue on?

PostCSS Custom Media Queries

### Plugin version

11.0

### What OS are you experiencing this on?

macOS

### Node Version

22

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
> Fixed negative resolutions in Media Queries to be invalid

This refers to the resolution feature, not negative queries in general.

`@media (resolution: -150dpi) {}`

But Safari only shipped support for media queries 4 in Safari 16.4
This includes `or`

-----

This might work:
- use comma separation instead of `or`
- use `screen and ... (...) and (...)` instead of `((...) and (...))`

```css
@custom-media --mobile (width <= 480px), screen and (height <= 480px) and (orientation: landscape);
@custom-media --tablet-plus screen and (width > 480px) and (height > 480px);

@media (--mobile), (--tablet-plus) {
  color:green;
}
```

https://preset-env.cssdb.org/playground/#JTdCJTIyc291cmNlJTIyJTNBJTIyJTQwY3VzdG9tLW1lZGlhJTIwLS1tb2JpbGUlMjAod2lkdGglMjAlM0MlM0QlMjA0ODBweCklMkMlMjBzY3JlZW4lMjBhbmQlMjAoaGVpZ2h0JTIwJTNDJTNEJTIwNDgwcHgpJTIwYW5kJTIwKG9yaWVudGF0aW9uJTNBJTIwbGFuZHNjYXBlKSUzQiU1Q24lNDBjdXN0b20tbWVkaWElMjAtLXRhYmxldC1wbHVzJTIwc2NyZWVuJTIwYW5kJTIwKHdpZHRoJTIwJTNFJTIwNDgwcHgpJTIwYW5kJTIwKGhlaWdodCUyMCUzRSUyMDQ4MHB4KSUzQiU1Q24lNUNuJTQwbWVkaWElMjAoLS1tb2JpbGUpJTJDJTIwKC0tdGFibGV0LXBsdXMpJTIwJTdCJTVDbiUyMCUyMGNvbG9yJTNBZ3JlZW4lM0IlNUNuJTdEJTIyJTJDJTIyY29uZmlnJTIyJTNBJTdCJTIyYnJvd3NlcnMlMjIlM0ElNUIlMjIlM0UlMjAwLjIlMjUlMjBhbmQlMjBub3QlMjBkZWFkJTIyJTVEJTJDJTIybWluaW11bVZlbmRvckltcGxlbWVudGF0aW9ucyUyMiUzQTAlMkMlMjJzdGFnZSUyMiUzQTIlMkMlMjJsb2dpY2FsJTIyJTNBJTdCJTIyaW5saW5lRGlyZWN0aW9uJTIyJTNBJTIybGVmdC10by1yaWdodCUyMiUyQyUyMmJsb2NrRGlyZWN0aW9uJTIyJTNBJTIydG9wLXRvLWJvdHRvbSUyMiU3RCU3RCU3RA==


This is not the same in all cases and we can't automatically transpile to that.
But in your case it might just be sufficient.

**Comment by romainmenke** [comment]
Happy to help!

Please let me know if that resolves your issue.

If it doesn't we will have to investigate further.
This plugin should work for older browser versions when using the older style of media queries.

**Comment by escaton** [comment]
It does — checked in 16.2 simulator.
So the root cause was using `or` from media queries 4.

**Comment by romainmenke** [comment]
Awesome,
thank you for confirming 🙇
