### ISSUE TITLE
After migration of postcss-preset-env from v6.7.0 to v7.4.1, how to add  color-mod-function support ?

### ISSUE THREAD

**Issue by ghost** [csstools/postcss-plugins#277]
### Bug description

Hi there, I am new to postcss plugins. I have to migrate `postcss-preset-env` from v6.7.0 to the latest v7.4.1
My postcss plugins stack for v6.7.0 looks like :-
```
                       const result = await postcss([
                              require('postcss-extend-rule')(),
                              require('postcss-advanced-variables')(),
                              require('postcss-preset-env')({
                                  stage: 0,
                                  features: {
                                      'color-mod-function': { unresolved: 'warn' },
                                  },
                              }),
                              require('postcss-atroot')(),
                              require('postcss-property-lookup')(),
                              require('postcss-nested')(),
                              require('postcss-hexrgba')(),
                              require('css-mqpacker')(),
                          ]).process(css, options);
```

When I bumped the version of `postcss-preset-env` to v7.4.1, I got to know that the color-mod-function support is removed. Could someone please suggest what should we use in place of it so that browser will recognize `color-mod` function.

i tried to have `color-function` in place of it but it is not working

### Expected Behavior

browser should recognize `color-mod` function

### What plugin are you experiencing this issue on?

PostCSS Preset Env

### Plugin version

7.4.1

### What OS are you experiencing this on?

macOS

### Node Version

12

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @mycodedig 

`postcss-color-mod` was deprecated because the specification died.
This means that browsers will never add support for it.

This might help you get unstuck :

https://github.com/romainmenke/postcss-preset-env-migrations

It has two pieces :
- [npm package](https://www.npmjs.com/package/postcss-preset-env-migrate-6.7.0-to-7) that contains the plugins you need
- [vscode extension](https://marketplace.visualstudio.com/items?itemName=RomainMenke.vscode-postcss-preset-env-migrations) to simplify updating your CSS source code.

The npm package will never be updated and is only intended to be used temporarily.
This makes it possible to update `postcss-preset-env` today and then take the next few weeks to update your source code.

**Comment by romainmenke** [comment]
Closing as user was deleted.

**Comment by tshakah** [comment]
What is the alternative to `color-mod`?
