### ISSUE TITLE
Add support for more math functions in calc

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#306]
### What would you want to propose?

WebKit added support for [calc() math functions](https://www.w3.org/TR/css-values-4/#trig-funcs) including sin, cos, tan, e, pi, exp, log, atan, acos, asin, and atan2.

### Suggested solution

A new plugin :)

### Additional context

https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/

https://www.w3.org/TR/css-values-4/#trig-funcs

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by Antonio-Laguna** [comment]
@jonathantneal yes and no.

No, because I didn't find that package till a month later since the package was released.
Yes because I knew some of those equations and I decided not to go with that.

Spec is quite strict around types, nested calc being possible, and multiple scenarios which I don't think the fallbacks would cut it. I _think_ there's value there as a last resort when you're using `var` but it's not easily testable (other than, produces expected output) or deterministic given `var` could be anything.
