### ISSUE TITLE
[postcss-cascade-layers] Does not correctly override cascade location

### ISSUE THREAD

**Issue by IanVS** [csstools/postcss-plugins#376]
### Bug description

I'm finding that using the `postcss-cascade-layers` plugin results in different styling than native css cascade layers. 

From the reproduction readme:

>Note that the button font is small.  This happens because layers are working.  The `defaults` layer has a lower priority than `components`, so even though the `.btn` styles occur lower in the import order than the css module (see `App.tsx`), it is overridden by the css module styling.
>
>However, if you uncomment `postcssCascadeLayers()` in `postcss.config.js` (and then stop and restart the dev server), you'll see this is no longer the case.  The `.btn` styles are applied, and the text size of the button is larger.

### Source CSS

See reproduction at https://github.com/IanVS/cascade-layer-postcss-issue-376

### Expected CSS

See reproduction

### Actual CSS

See reproduction

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

N/A

### What plugin are you experiencing this issue on?

PostCSS Cascade Layers

### Plugin version

1.0.0

### What OS are you experiencing this on?

macOS

### Node Version

16.14.2

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @IanVS,

Thank you for bringing this up!

Unfortunately this is not something we can resolve.
To apply the correct specificity to each rule, the entirety of your CSS needs to be exposed to the PostCSS plugin in a single pass.

If styles have different entry points it will most likely not work correctly.

When you import all styles in `index.css` you will see that the plugin does work correctly :

```css
@layer defaults, theme, patterns, components, utilities, overrides;

@import url('default-styles.css') layer(defaults);

@import url('App.css');
@import url('App.module.css');
```

---------

The plugin does many analysis and desugaring passes in pursuit of this information :

- what is the most specific selector for all the styles
- what is the order in which layers are defined

If not all the CSS is visible to the plugin at once, either or both of these things will be incorrect.

---------

We can definitely document this behaviour better on the plugin README so that people are more aware of this.

**Comment by IanVS** [comment]
Ok, I see, thank you for explaining.  Maybe this issue can stay open until the readme is updated, in case others come across this as well?

**Comment by romainmenke** [comment]
Hi @IanVS 

We have updated the docs for the plugin : https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-cascade-layers#how-it-works

Any feedback on this would be appreciated :)

**Comment by IanVS** [comment]
Thank you, that's very helpful!
