### ISSUE TITLE
exportTo not running when used as plugin

### ISSUE THREAD

**Issue by jenshedqvist** [csstools/postcss-plugins#414]
I'm using the PostCSS CLI with a postcss.config.js and the `exportTo` option doesn't seem to be running at all. I get no error in the console. This is my config:

```javascript
module.exports = (ctx) => ({
  map: ctx.options.map,
  plugins: [
    require('postcss-import')({
      path: ['src']
    }),
    require('postcss-custom-properties')(),
    require('postcss-responsive-type')(),
    require('postcss-selector-matches')(),
    require('postcss-custom-media')({
      exportTo: 'src/tokens/custom-media.js'
    }),
    require('postcss-color-function')(),
    require('postcss-object-fit-images')(),
    require('postcss-url')([
      { filter: '**/*.woff', url: 'inline' },
      { url: 'copy', useHash: true }
    ]),
    require('postcss-flexbugs-fixes')(),
    require('autoprefixer')({ browsers: [ 'last 2 versions', 'ie >= 10', 'Firefox ESR' ] }),
    require('postcss-clean')()
  ]
})
```

And the NPM Scripts command:
```bash
"build-css": "postcss src/components/app/index.css --no-map -c postcss.config.js -o static/build/css/site.min.css",```
```

**Comment by romainmenke** [comment]
@jenshedqvist It's been an incredibly long time since anyone looked at this issue, sorry about that.

We will not able to create a reproduction for this.
But if (by chance) you are still encountering this specific issue, please let us know and we will reopen this!

If you encounter any other issues with `postcss-custom-media` we are also happy to investigate and provide support!
