### ISSUE TITLE
`oklch` value not converted with variables

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#507]
it looks like the test suite does not convert this:

```css
--firebrick-var: oklch(40% var(--point-five) 0.1324 / var(--opacity-50));
```

Not sure if that's a bug or not. It supports variables for the opacity but not the LCH values.

_Originally posted by @jokull in https://github.com/csstools/postcss-plugins/issues/246#issuecomment-1168591819_

**Comment by romainmenke** [comment]
@jokull Going to close this one as there isn't anything to fix here :)

**Comment by dwighthouse** [comment]
Might I suggest a possible solution that could get you 90% there?

What if there was a way to specify that for some css variables (via specification of names, or by defining a variable naming pattern), we assure PostCSS that a variable is constant and global? If so, something like postcss-calc could be used to aggressively apply calc statements for these variables where it normally wouldn't. If no variables remain in a processed value, then the color can be treated as static and converted down to display-p3 and hex code fallbacks as appropriate, as what happens when css variable has a whole oklch value.

For example, given the input:
```
:root {
    --__brand-hue: 270;
    --warning-hue: 101;
    --primary-color: oklch(52% 0.21 var(--__brand_hue);
    --warning-color: oklch(86.32% 0.15 var(--warning-hue));
}
```

The output might be:
```
:root {
    --__brand-hue: 270;
    --warning-hue: 101;
    --primary-color: rgb(62, 85, 223);
    --warning-color: oklch(86.32% 0.15 var(--warning-hue));
}

@supports (color: color(display-p3 0 0 0)) {
    :root {
        --primary-color: color(display-p3 0.26256 0.33170 0.84336);
    }
}
```

**Comment by romainmenke** [comment]
Hi @dwighthouse 
Thank you for your interest in this issue!

This is unfortunately not something that we can do.
The plugins are polyfills and fallbacks that must work reliably and predictably for millions of developers.

But it is something that you can do.
You can run `postcss-custom-properties` manually and before `postcss-preset-env`.
By setting `{ preserve: false }` this plugin will replace as many `var()` as possible : https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-custom-properties#options

If you want control over which properties get replaced it would make sense to fork and publish that plugin and build in the extra features you require. Creating a spinoff plugin is a great way to offer a more specialized feature.

**Comment by dwighthouse** [comment]
@romainmenke That makes sense. Thanks for letting me know about this.
