### ISSUE TITLE
Fix dependency versions!

### ISSUE THREAD

**Issue by 6562680** [csstools/postcss-plugins#508]
You write in devlog that
7.4.4 -> updated autoprefixer to 10.4.5

But actually you use ^10.4.5 that means 10.4.x.

You have to use CERTAIN version without any X and "^". If you trust devs - only then you have to use "^10.4" or something

It was updated to 10.4.7 and now it always write warning "replace color-adjust to print-color-adjust [deprecated]" and each production build ends with "warning".

Possible solutions is `package.json`:
```
{
  resolutions: {
    autoprefixer: "10.4.5"
  }
}
```
but even then you got a warning that "resolutions for 10.4.5 is incompatible with 10.4.7"

(the world is a big piece of sh*t, you have to learn in a whole life)

**Comment by Antonio-Laguna** [comment]
@6562680 what `^` implies is that it should be _at least_ `10.4.5` and from there the latest version that's not breaking. That means you should be able to set a hard dependency on `10.4.5` by setting either `dependencies` or `devDependencies` to have `autoprefixer: '10.4.5'` and you shouldn't get any validation errors from NPM.

If you're still struggling, could you paste the content of `package.json` so I can help?

**Comment by ehoogeveen-medweb** [comment]
IIRC semantic version numbers actually have the format `major.minor.patch` and caret (`^`) dependency allows both `minor` and `patch` to be higher than the specified version. A tilde (`~`) dependency only allows the `patch` version to change.

So the only part of the version number that is actually protected is the `major` version - which is why projects that adhere to semantic versioning need to increment the `major` version on every incompatible API change.

Of course, things do occasionally break in practice. If a dependency's `minor` or `patch` version changes and causes an error, you can install it as a direct dependency and pin the version (by removing the caret or tilde). Then npm's automatic deduplication should remove newer versions as long as they're compatible (you can make the deduplication more aggressive by using `npm install --prefer-dedupe` or explicitly running `npm dedupe`).

**Comment by romainmenke** [comment]
@6562680 Going to close this issue as there is nothing more we can fix on our end here.
The changelogs have been updated.

Thank you again for bringing this up!
