### ISSUE TITLE
postcss-custom-properties v13.0.0?

### ISSUE THREAD

**Issue by gjvoosten** [csstools/postcss-plugins#708]
According to [npm](https://www.npmjs.com/package/postcss-custom-properties), postcss-custom-properties v13.0.0 was published but there's no trace of it in the source code at https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-custom-properties :fearful:

**Comment by Antonio-Laguna** [comment]
@gjvoosten thanks for reaching out! You can see the source code here: https://github.com/csstools/postcss-plugins/tree/postcss-preset-env--v8/plugins/postcss-custom-properties

We've been working on a version 8 of postcss-preset-env that will break multiple packages. We've been announcing these packages and releasing alphas of postcss-preset-env so that there's enough time to migrate.

You can see in the [CHANGELOG](https://github.com/csstools/postcss-plugins/blob/postcss-preset-env--v8/plugins/postcss-custom-properties/CHANGELOG.md#1300-november-14-2022) the changes to version 13

**Comment by Antonio-Laguna** [comment]
@gjvoosten also forgot to add that we've been crafting a Wiki with expanded information on our reasoning, what has changed, and how to migrate if applicable. You can find the wiki here: https://github.com/csstools/postcss-plugins/wiki/PostCSS-Preset-Env-8

**Comment by gjvoosten** [comment]
Thanks, appreciated. Perhaps a notice in the main [README.md](https://github.com/csstools/postcss-plugins/blob/main/plugins/postcss-custom-properties/README.md) would be nice?

**Comment by romainmenke** [comment]
I've pinned the issue with more info about the process : https://github.com/csstools/postcss-plugins/issues/461

Hopefully this helps enough so that we don't have to update the readme of each updated plugin :)
