### ISSUE TITLE
postcss-logical-float-and-clear not including [dir="rtl"] version of ruleset

### ISSUE THREAD

**Issue by mherchel** [csstools/postcss-plugins#958]
### Bug description

I'm not sure if this is a bug or a feature (because [the documentation](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-logical-float-and-clear) doesn't say that this should be compiled this way)

The issue is that PostCSS Logical ~will~ *used to* compile CSS and include RTL versions (assuming default is LTR). 

Example source:
```
.test { padding-inline-start: 10px; }
```
Example output: 
```
.test { padding-left: 10px; }
[dir="rtl"] .test { padding-right: 10px; }
```
However, I can't see any option within PostCSS Logical Float And Clear to do the same. 

### Source CSS

.test { float: inline-start; }

### Expected CSS

.test { float: left; }
[dir="rtl"] .test { float: right; }

### Actual CSS

.test { float: left; }

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

N/A

### What plugin are you experiencing this issue on?

PostCSS Preset Env, PostCSS Logical Float and Clear

### Plugin version

1.0.1

### What OS are you experiencing this on?

macOS

### Node Version

16.13.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by mherchel** [comment]
Note that it looks like PostCSS Logical doesn't do a [dir="rtl"] prefix anymore. It appears that this change appeared in #740, but the link to the Changelog is broken

**Comment by romainmenke** [comment]
>  Is there a way to revert to that behavior though?

No.

But there is one alternative we are considering.
see : https://github.com/csstools/postcss-plugins/issues/892#issuecomment-1479024579

You write selectors with `[dir]` and use logical props/values inside those rules.
Then the plugin could generate fallbacks with `[dir=ltr]` and `[dir=rtl]`.

The specificity would remain the same, so it doesn't have that specific issue.

But this approach still suffers from bloated outputs.
Because one rule generates two new rules you easily get a lot of bloat.

------

Is it possible to generate multiple output stylesheets for Drupal core?
One for ltr, one for rtl, ...

And then leave it up to theme builders / users to include the correct one depending on settings, ...

**Comment by romainmenke** [comment]
Also a valid approach is to fork the old logical plugin and keep using it directly (not through PostCSS Preset Env).

This allows you to keep using `dir` while also having access to the latest features from PostCSS Preset Env.

The source code can be found on the `postcss-preset-env--v7` branch :
https://github.com/csstools/postcss-plugins/tree/postcss-preset-env--v7/plugins/postcss-logical

If you do decide to fork from that point we are happy to assist in any way.

**Comment by mherchel** [comment]
Thanks for the response. At this point all of our supported browsers support logical properties (yay!) except for `float`, `clear`, etc, and tbh, there's not too much more of that. My thought is we'll just keep as-is until browser vendors include this. 

Thanks again for all of the excellent work here :D
